# ========================================================================================
# SITE CONFIGURATION
# ========================================================================================

url: https://berenice-lm.github.io
lang: fr
title: La progressivité
description: >
  à écrire
tagline: Site de vulgarisation scientifique
keywords: [cartographie]
logo: /assets/img/icon.gif

author:
  name: Bérénice Le Mao
  email: mail@domain.tld

menu:
  - title: La progressivité dans les médias
    url: /progressivite/
  - title: Les piliers de la progressivité
    url: /piliers/
  - title: Expériences cartographiques
    url: /experiences/
  - title: Écouter une carte pan-scalaire
    url: /musique/
  - title: La progressivité en BD
    url: /BD/

legal:
  - title: LICENSE
    url: /LICENSE/
  - title: Les piliers de la progressivité
    url: /piliers/
  - title: La progressivité dans les autres médias
    url: /progressivite/

copyright: © 2024. All rights reserved.
permalink: /:categories/:year-:month-:day-:title/
paginate: 10
paginate_path: /:num/

# ========================================================================================
# THEME
# ========================================================================================

# Le thème Hydejack est chargé localement via le Gemfile
theme: jekyll-theme-hydejack

# ========================================================================================
# APPEARANCE
# ========================================================================================

accent_image: /assets/img/background2.jpg
accent_image_overlay: false
accent_color: rgb(79,177,186)
theme_color: rgb(25,55,71)

# ========================================================================================
# KRAMDOWN (MATH)
# ========================================================================================

kramdown:
  math_engine: katex
  math_engine_opts: {}
  footnote_backlink: '&#x21a9;&#xfe0e;'

# ========================================================================================
# HYDEJACK SETTINGS
# ========================================================================================

# hydejack:
#   post_addons: [related, random]
#   project_addons: []
#   no_mark_external: false
#   no_push_state: false
#   no_drawer: false
#   no_navbar: false
#   no_search: false
#   no_inline_css: false
#   no_page_style: false
#   no_break_layout: true
#   no_toc: false
#   no_third_column: false
#   no_large_headings: false
#   no_structured_data: false
#   no_theme_color: false
#   no_breadcrumbs: false
#   use_lsi: true
#   cookies_banner: false
#   advertise: false
#   hide_dates: false
#   hide_last_modified: false
#   dark_mode:
#     always: false
#     dynamic: true
#     icon: true
#   offline:
#     enabled: false
#     cache_version: 13
#     precache_assets:
#       - /assets/img/swipe.svg

# ========================================================================================
# COLLECTIONS
# ========================================================================================

collections:
  featured_categories:
    permalink: /:name/
    output: true
  featured_tags:
    permalink: /tag-:name/
    output: true
  example:
    output: true
    permalink: /example/:path/
  experiences:
    output: true
    permalink: /experiences/:path/

# ========================================================================================
# PLUGINS
# ========================================================================================

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache
  - jekyll-last-modified-at

# ========================================================================================
# OTHER SETTINGS
# ========================================================================================

sass:
  style: compressed

favicon: /assets/img/favicon.ico
